// <auto-generated />
namespace TreKa.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IncreasedMaxLength60 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncreasedMaxLength60));
        
        string IMigrationMetadata.Id
        {
            get { return "201805251610462_Increased-MaxLength-60"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
