// <auto-generated />
namespace TreKa.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedColumnRepetition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedColumnRepetition));
        
        string IMigrationMetadata.Id
        {
            get { return "201805251505267_Added-Column-Repetition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
